### ISSUE TITLE
Result filtering based on benign functions

### ISSUE THREAD

**Issue by yankovs** [danielplohmann/mcrit#34]
Hey!

Awesome project! I've been reading the code and wondering, is there currently any way to filter benign functions using mcrit?  

Let's say I keep a repository of functions extracted from compiler boilerplate and the such (much like `mcrit-data`). Is there any way, when I index some malware sample, to basically remove these functions from the malware sample? Ideally, I'd like the mcrit DB to index only "interesting" functions from the binary and make a minhash based on that.

Maybe mcrit works in a different manner than what I'm thinking about so my question is not relevant, but it would be nice to know either way

**Comment by danielplohmann** [comment]
Hi!
Thanks for the kind words!

Yes, there is such functionality and its one of the primary purposes of MCRIT.
In MCRIT you can tag samples and families as "library", which will then automatically enable such filtering like you described.
 
Let's go with an example, i think that will be most illustrative.
Didn't find a perfect one, but this one works.
We start with an unpacked PseudoManuscrypt sample, simply because it's using libzlib:

```
$ grep -ao "inflate.*Mark Adler" malpedia/win.pseudo_manuscrypt/2021-05-11/820e6cabe7ab6288d67fbb6c424c701c443cbd9161b0c47c9cfdbaf6fc3cd91d_unpacked
inflate 1.2.11 Copyright 1995-2017 Mark Adler
```
Now, we want to filter out libzlib and ideally also the MSVCRT code.
Looking at the PE header, it has MajorLinker version 12, sadly we don't have MSVC2015 covered in [mcrit-data](https://github.com/danielplohmann/mcrit-data) yet, but you can simply take the binaries from my other project [empty_msvc](https://github.com/danielplohmann/empty_msvc).

Load everything in MCRIT, so you end up with something like this (notice how all samples except the malware are tagged library in the table):

![image](https://github.com/danielplohmann/mcrit/assets/9798598/a9a4f480-fcde-4bbf-98f6-79c7df4a78be)

Now we can do a 1:N matching of the malware sample and end up with this report:

![image](https://github.com/danielplohmann/mcrit/assets/9798598/340ca925-1399-4d82-8efa-03ae4f1767f5)

We don't match any malware, because we loaded up only one malware sample, but we see that a good amount of library code was matched (24%+6%).
This is also shown in the MCRIT diagram. 
It's not that intuitive, but once you know how to read it, I think it's informative. :D 
* Upper row is which functions matched at all and in how many other families they matched (blue here means only on one other family, which is simply a result of the lack of data)
* Middle row indicates whether the match was a library match or not. Green indicates that one library was matched, red that multiple were matched (sometimes, you will have same algorithms in multiple reference code data sets)
* Bottom row gives the best score that was matched (blue is a PIC hash based matched, so even instruction bytes are similar, color/score then goes down via blue, green, yellow, orange, red).

Short Digression: Now filtering down to an arbitrary function in the lower table, you can get to the individual comparison view to verify matches. Here's how the _inflate_table was properly matched:

![image](https://github.com/danielplohmann/mcrit/assets/9798598/39a6a5bc-60a8-4a80-a138-b5e12cb537b3)

Now, despite us having reference code with the same libzlib version and even compiled with the same MSVC version, code can/will still be different in many cases but the matching is typically sufficient to get a good assignment.

Now, let's assume you have a bigger database, for example the one I use for development (loaded with all of Malpedia).
I don't have another win.pseudo_manuscrypt sample at hand, but a memory dump of the same sample.
In such a case, the upper matching table may look something like this:

![image](https://github.com/danielplohmann/mcrit/assets/9798598/dfb56e21-74be-4a18-8813-09157a84635c)

In this case, we see that the other sample expectedly matched almost identically (direct score of 98%) but more interesting is probably the Frequency result here. Since MCRIT also discounts matches that occur in many other families, we get a strong 53% here (compared to all other families with 5% and less), and when doing matching with library matched filtered out, this even rises to 76%.
I guess that's going in the direction of what you were asking? 
Otherwise, that's also covered in the [documentation](https://github.com/fkie-cad/mcritweb/tree/master/documentation) and in the presentation I gave at [botconf](https://youtu.be/kvBHbXZZq2c?t=1383).

Hope that helps, otherwise happy to discuss further.

**Comment by yankovs** [comment]
Thank you for the very thorough answer! It was exactly what I was looking for 🚀 .
I am curious about one other thing, I'll ask here to not pollute with too many issues.

How does `mcrit` deal with simultaneous indexing and querying? I'm looking at the possibility of having some ongoing indexing process to feed `mcrit` with samples. Ideally, I'd like to keep querying for similarity results.

Thank you!

**Comment by danielplohmann** [comment]
Both processing samples and full sample query/matching (not individual functions/blocks) are asynchronous jobs that are processed in a queue. So unless you flood MCRIT with samples, it should not be an issue to run queries/matching jobs inbetween and get results very near time. There is however no way to rank/boost priority of individual jobs currently, that might be something possibly worth considering for the future.
