### ISSUE TITLE
IDA plugin exception printing

### ISSUE THREAD

**Issue by malwarefrank** [danielplohmann/mcrit#67]
The numerous `print(traceback.format_exc(exc))` calls in `plugins/ida/helpers/McritInterface.py` are themselves causing exceptions.  It looks like [traceback.format_exc does not take an exception as an argument](https://docs.python.org/3/library/traceback.html#traceback.format_exc).  Did you mean to use `print(traceback.format_exc())` without an argument, or maybe `print("".join(traceback.format_exception(exc)))` or maybe `traceback.print_exc()`?

**Comment by danielplohmann** [comment]
Haha, now I feel like a dinosaur.
I think `print(traceback.format_exc(exc))` was a valid way in Python2 that I tended to use and somehow when I wrote these lines it was probably the first thing that came to my mind. Also not helpful that my local test didn't trigger any of that measly attempts of exception printing...
Anyhow, I guess that's fixed with the next push.
